# Makefile.in generated by automake 1.13.4 from Makefile.am.
# src/sst/elements/booksim2/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# -*- Makefile -*-
#
#


am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/sst-elements-library
pkgincludedir = $(includedir)/sst-elements-library
pkglibdir = $(libdir)/sst-elements-library
pkglibexecdir = $(libexecdir)/sst-elements-library
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
subdir = src/sst/elements/booksim2
DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/Makefile.am \
	$(top_srcdir)/config/depcomp
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/config/argz.m4 \
	$(top_srcdir)/config/libtool.m4 $(top_srcdir)/config/ltdl.m4 \
	$(top_srcdir)/config/ltoptions.m4 \
	$(top_srcdir)/config/ltsugar.m4 \
	$(top_srcdir)/config/ltversion.m4 \
	$(top_srcdir)/config/lt~obsolete.m4 \
	$(top_srcdir)/config/sst-check_picky.m4 \
	$(top_srcdir)/config/sst_check_cuda.m4 \
	$(top_srcdir)/config/sst_check_dramsim.m4 \
	$(top_srcdir)/config/sst_check_dramsim3.m4 \
	$(top_srcdir)/config/sst_check_dumpi.m4 \
	$(top_srcdir)/config/sst_check_fdsim.m4 \
	$(top_srcdir)/config/sst_check_goblin_hmcsim.m4 \
	$(top_srcdir)/config/sst_check_gpgpusim.m4 \
	$(top_srcdir)/config/sst_check_hbmdramsim.m4 \
	$(top_srcdir)/config/sst_check_hybridsim.m4 \
	$(top_srcdir)/config/sst_check_libphx.m4 \
	$(top_srcdir)/config/sst_check_libz.m4 \
	$(top_srcdir)/config/sst_check_nvdimmsim.m4 \
	$(top_srcdir)/config/sst_check_otf.m4 \
	$(top_srcdir)/config/sst_check_otf2.m4 \
	$(top_srcdir)/config/sst_check_pintool.m4 \
	$(top_srcdir)/config/sst_check_ptrace_set_tracer.m4 \
	$(top_srcdir)/config/sst_check_ramulator.m4 \
	$(top_srcdir)/config/sst_check_shm.m4 \
	$(top_srcdir)/config/sst_check_stake.m4 \
	$(top_srcdir)/config/sst_core_check_install.m4 \
	$(top_srcdir)/config/sst_elements_config_output.m4 \
	$(top_srcdir)/config/sst_os_check_osx.m4 \
	$(top_srcdir)/config/sst_elements_include.m4 \
	$(top_srcdir)/src/sst/elements/ariel/configure.m4 \
	$(top_srcdir)/src/sst/elements/balar/configure.m4 \
	$(top_srcdir)/src/sst/elements/ember/configure.m4 \
	$(top_srcdir)/src/sst/elements/memHierarchy/configure.m4 \
	$(top_srcdir)/src/sst/elements/Messier/configure.m4 \
	$(top_srcdir)/src/sst/elements/miranda/configure.m4 \
	$(top_srcdir)/src/sst/elements/prospero/configure.m4 \
	$(top_srcdir)/src/sst/elements/Samba/configure.m4 \
	$(top_srcdir)/src/sst/elements/VaultSimC/configure.m4 \
	$(top_srcdir)/src/sst/elements/zodiac/configure.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/src/sst_element_config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(compdir)"
LTLIBRARIES = $(comp_LTLIBRARIES)
libbooksim2_la_LIBADD =
am__dirstamp = $(am__leading_dot)dirstamp
am_libbooksim2_la_OBJECTS = booksim2.lo booksimBridge.lo \
	booksimInterface.lo src/allocators/allocator.lo \
	src/allocators/islip.lo src/allocators/loa.lo \
	src/allocators/maxsize.lo src/allocators/pim.lo \
	src/allocators/selalloc.lo \
	src/allocators/separable_input_first.lo \
	src/allocators/separable.lo src/allocators/wavefront.lo \
	src/arbiters/arbiter.lo src/arbiters/matrix_arb.lo \
	src/arbiters/prio_arb.lo src/arbiters/roundrobin_arb.lo \
	src/arbiters/tree_arb.lo src/learning/dgb.lo \
	src/networks/anynet.lo src/networks/cmesh.lo \
	src/networks/dragonfly.lo src/networks/fattree.lo \
	src/networks/flatfly_onchip.lo src/networks/fly.lo \
	src/networks/kncube.lo src/networks/network.lo \
	src/networks/qtree.lo src/networks/tree4.lo \
	src/power/buffer_monitor.lo src/power/power_module.lo \
	src/power/switch_monitor.lo src/routers/chaos_router.lo \
	src/routers/event_router.lo src/routers/iq_router.lo \
	src/routers/router.lo src/batchtrafficmanager.lo \
	src/booksim_config.lo src/buffer_state.lo src/buffer.lo \
	src/config_utils.lo src/credit.lo src/flit.lo \
	src/flitchannel.lo src/injection.lo src/misc_utils.lo \
	src/module.lo src/outputset.lo src/packet_reply_info.lo \
	src/random_utils.lo src/rng_double_wrapper.lo \
	src/rng_wrapper.lo src/routefunc.lo src/stats.lo \
	src/traffic.lo src/trafficmanager.lo src/vc.lo
libbooksim2_la_OBJECTS = $(am_libbooksim2_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
libbooksim2_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
	$(AM_CXXFLAGS) $(CXXFLAGS) $(libbooksim2_la_LDFLAGS) \
	$(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I. -I$(top_builddir)/src
depcomp = $(SHELL) $(top_srcdir)/config/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(libbooksim2_la_SOURCES)
DIST_SOURCES = $(libbooksim2_la_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /home/hanskasan/Research/Latest_SST/scratch/src/sst-elements-library-11.0.0/config/missing aclocal-1.13
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
AR = ar
ARGZ_H = 
AUTOCONF = ${SHELL} /home/hanskasan/Research/Latest_SST/scratch/src/sst-elements-library-11.0.0/config/missing autoconf
AUTOHEADER = ${SHELL} /home/hanskasan/Research/Latest_SST/scratch/src/sst-elements-library-11.0.0/config/missing autoheader
AUTOMAKE = ${SHELL} /home/hanskasan/Research/Latest_SST/scratch/src/sst-elements-library-11.0.0/config/missing automake-1.13
AWK = gawk
BOOST_LIB_SUFFIX = 
CC = /home/hanskasan/bin/bin/gcc
CCDEPMODE = depmode=gcc3
CC_VERSION = gcc (GCC) 9.1.0
CFLAGS = -g -O2  
CPP = /home/hanskasan/bin/bin/gcc -E
CPPFLAGS =   -I/usr/include/python2.7 -I/usr/include/python2.7  -I/home/hanskasan/Research/Latest_SST/local/sstcore-11.0.0/include/sst/core -I/home/hanskasan/Research/Latest_SST/local/sstcore-11.0.0/include
CUDA_CPPFLAGS = 
CUDA_LDFLAGS = 
CUDA_LIBDIR = 
CUDA_LIBS = 
CXX = /home/hanskasan/bin/bin/g++
CXXCPP = /home/hanskasan/bin/bin/g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2  -std=c++1y -D__STDC_FORMAT_MACROS 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DRAMSIM3_CPPFLAGS = 
DRAMSIM3_LDFLAGS = 
DRAMSIM3_LIB = 
DRAMSIM3_LIBDIR = 
DRAMSIM_CPPFLAGS = 
DRAMSIM_LDFLAGS = 
DRAMSIM_LIB = 
DRAMSIM_LIBDIR = 
DSYMUTIL = 
DUMPBIN = 
DUMPI_CPPFLAGS = 
DUMPI_LDFLAGS = 
DUMPI_LIB = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
FDSIM_CPPFLAGS = 
FDSIM_CXXFLAGS = 
FDSIM_LDFLAGS = 
FDSIM_LIB = 
FDSIM_LIBDIR = 
FGREP = /usr/bin/grep -F
GOBLIN_HMCSIM_CPPFLAGS = 
GOBLIN_HMCSIM_LDFLAGS = 
GOBLIN_HMCSIM_LIB = 
GOBLIN_HMCSIM_LIBDIR = 
GPGPUSIM_CPPFLAGS = 
GPGPUSIM_LDFLAGS = 
GPGPUSIM_LIB = 
GPGPUSIM_LIBDIR = 
GREP = /usr/bin/grep
HAVE_SET_PTRACER = 1
HBMDRAMSIM_CPPFLAGS = 
HBMDRAMSIM_LDFLAGS = 
HBMDRAMSIM_LIB = 
HBMDRAMSIM_LIBDIR = 
HYBRIDSIM_CPPFLAGS = 
HYBRIDSIM_LDFLAGS = 
HYBRIDSIM_LIB = 
HYBRIDSIM_LIBDIR = 
INCLTDL = -I${top_srcdir}/src/libltdl
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS =    -lpthread -ldl -lutil -lm -lpython2.7 -Xlinker -export-dynamic
LIBADD_DL = -ldl 
LIBADD_DLD_LINK = 
LIBADD_DLOPEN = -ldl
LIBADD_SHL_LOAD = 
LIBLTDL = ${top_build_prefix}src/libltdl/libltdlc.la
LIBOBJS = 
LIBPHX_CPPFLAGS = 
LIBPHX_LDFLAGS = 
LIBPHX_LIB = 
LIBPHX_LIBDIR = 
LIBS = -ldl   -ldl 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBZ_CPPFLAGS = 
LIBZ_LDFLAGS = 
LIBZ_LIB = -lz
LIPO = 
LN_S = ln -s
LTDLDEPS = ${top_build_prefix}src/libltdl/libltdlc.la
LTDLINCL = -I${top_srcdir}/src/libltdl
LTDLOPEN = libltdl
LTLIBOBJS = 
LT_CONFIG_H = src/sst_element_config.h
LT_DLLOADERS =  dlopen.la
LT_DLPREOPEN = -dlpreopen dlopen.la 
MAKEINFO = ${SHELL} /home/hanskasan/Research/Latest_SST/scratch/src/sst-elements-library-11.0.0/config/missing makeinfo
MANIFEST_TOOL = :
MKDIR_P = /usr/bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
NVDIMMSIM_CPPFLAGS = 
NVDIMMSIM_CXXFLAGS = 
NVDIMMSIM_LDFLAGS = 
NVDIMMSIM_LIB = 
NVDIMMSIM_LIBDIR = 
OBJDUMP = objdump
OBJEXT = o
OTF2_CONFIG_TOOL = 
OTF2_CPPFLAGS = 
OTF2_LDFLAGS = 
OTF2_PATH = 
OTF_CONFIG_TOOL = 
OTF_CPPFLAGS = 
OTF_LDFLAGS = 
OTF_PATH = 
OTOOL = 
OTOOL64 = 
PACKAGE = sst-elements-library
PACKAGE_BUGREPORT = sst@sandia.gov
PACKAGE_NAME = SST Elements Library
PACKAGE_STRING = SST Elements Library 11.0.0
PACKAGE_TARNAME = sst-elements-library
PACKAGE_URL = 
PACKAGE_VERSION = 11.0.0
PATH_SEPARATOR = :
PINTOOL2_RUNTIME = 
PINTOOL3_RUNTIME = 
PINTOOL_CPPFLAGS = 
PINTOOL_DIR = 
PINTOOL_LDFLAGS = 
PINTOOL_PATH = /home/hanskasan/Research/Latest_SST/local/sstcore-11.0.0/bin:/usr/lib64/qt-3.3/bin:/home/hanskasan/perl5/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/hanskasan/.local/bin:/home/hanskasan/bin
PINTOOL_RUNTIME = 
RAMULATOR_CPPFLAGS = 
RAMULATOR_LDFLAGS = 
RAMULATOR_LIB = 
RAMULATOR_LIBDIR = 
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
SHM_LIB = -lrt -ldl   -ldl 
SSTELEMENTS_GIT_BRANCH = N/A
SSTELEMENTS_GIT_COMMITCOUNT = 0
SSTELEMENTS_GIT_HEADSHA = 11.0.0
SST_ACTIVE_ELEMENT_LIBRARIES =  booksim2 ember firefly hermes kingsley merlin simpleElementExample simpleSimulation
SST_CONFIG_TOOL = /home/hanskasan/Research/Latest_SST/local/sstcore-11.0.0/bin/sst-config
SST_DIST_ELEMENT_LIBRARIES =  ariel balar booksim2 cacheTracer cassini CramSim ember firefly hermes kingsley memHierarchy merlin Messier miranda prospero Samba shogun simpleElementExample simpleSimulation thornhill vanadis VaultSimC zodiac
SST_PREFIX = /home/hanskasan/Research/Latest_SST/local/sstcore-11.0.0
SST_REGISTER_TOOL = /home/hanskasan/Research/Latest_SST/local/sstcore-11.0.0/bin/sst-register
STAKE_CPPFLAGS = 
STAKE_LDFLAGS = 
STAKE_LIB = 
STAKE_LIBDIR = 
STRIP = strip
VERSION = 11.0.0
abs_builddir = /home/hanskasan/Research/Latest_SST/scratch/src/sst-elements-library-11.0.0/src/sst/elements/booksim2
abs_srcdir = /home/hanskasan/Research/Latest_SST/scratch/src/sst-elements-library-11.0.0/src/sst/elements/booksim2
abs_top_builddir = /home/hanskasan/Research/Latest_SST/scratch/src/sst-elements-library-11.0.0
abs_top_srcdir = /home/hanskasan/Research/Latest_SST/scratch/src/sst-elements-library-11.0.0
ac_ct_AR = ar
ac_ct_CC = /home/hanskasan/bin/bin/gcc
ac_ct_CXX = 
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = tar --format=posix -chf - "$$tardir"
am__untar = tar -xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/hanskasan/Research/Latest_SST/scratch/src/sst-elements-library-11.0.0/config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
ltdl_LIBOBJS =  lt__strl.o
ltdl_LTLIBOBJS =  lt__strl.lo
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /home/hanskasan/Research/Latest_SST/local/sstelements-11.0.0
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sys_symbol_underscore = no
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../../../../
top_builddir = ../../../..
top_srcdir = ../../../..
AM_CPPFLAGS = \
	$(MPI_CPPFLAGS) -D SINGLE_CYCLE -D DGB_ON

compdir = $(pkglibdir)
comp_LTLIBRARIES = libbooksim2.la
libbooksim2_la_SOURCES = \
	booksim2.cc \
	booksimBridge.cc \
	booksimInterface.cc \
	src/allocators/allocator.cpp \
  	src/allocators/islip.cpp \
  	src/allocators/loa.cpp \
  	src/allocators/maxsize.cpp \
  	src/allocators/pim.cpp \
  	src/allocators/selalloc.cpp \
  	src/allocators/separable_input_first.cpp \
  	src/allocators/separable.cpp \
  	src/allocators/wavefront.cpp \
  	src/arbiters/arbiter.cpp \
    src/arbiters/matrix_arb.cpp \
    src/arbiters/prio_arb.cpp \
    src/arbiters/roundrobin_arb.cpp \
    src/arbiters/tree_arb.cpp \
	src/learning/dgb.cpp \
  	src/networks/anynet.cpp \
    src/networks/cmesh.cpp \
    src/networks/dragonfly.cpp \
    src/networks/fattree.cpp \
    src/networks/flatfly_onchip.cpp \
    src/networks/fly.cpp \
    src/networks/kncube.cpp \
    src/networks/network.cpp \
    src/networks/qtree.cpp \
    src/networks/tree4.cpp \
  	src/power/buffer_monitor.cpp \
    src/power/power_module.cpp \
    src/power/switch_monitor.cpp \
  	src/routers/chaos_router.cpp \
    src/routers/event_router.cpp \
    src/routers/iq_router.cpp \
    src/routers/router.cpp \
  	src/batchtrafficmanager.cpp \
  	src/booksim_config.cpp \
    src/buffer_state.cpp \
  	src/buffer.cpp \
  	src/config_utils.cpp \
  	src/credit.cpp \
  	src/flit.cpp \
  	src/flitchannel.cpp \
  	src/injection.cpp \
  	src/misc_utils.cpp \
  	src/module.cpp \
  	src/outputset.cpp \
  	src/packet_reply_info.cpp \
  	src/random_utils.cpp \
	src/rng_double_wrapper.cpp \
	src/rng_wrapper.cpp \
  	src/routefunc.cpp \
  	src/stats.cpp \
  	src/traffic.cpp \
  	src/trafficmanager.cpp \
  	src/vc.cpp \
	booksim2.h \
	booksimBridge.h \
	booksimInterface.h \
	src/allocators/allocator.hpp \
  	src/allocators/islip.hpp \
  	src/allocators/loa.hpp \
  	src/allocators/maxsize.hpp \
  	src/allocators/pim.hpp \
  	src/allocators/selalloc.hpp \
  	src/allocators/separable_input_first.hpp \
  	src/allocators/separable.hpp \
  	src/allocators/wavefront.hpp \
  	src/arbiters/arbiter.hpp \
    src/arbiters/matrix_arb.hpp \
    src/arbiters/prio_arb.hpp \
    src/arbiters/roundrobin_arb.hpp \
    src/arbiters/tree_arb.hpp \
	src/learning/dgb.hpp \
  	src/networks/anynet.hpp \
    src/networks/cmesh.hpp \
    src/networks/dragonfly.hpp \
    src/networks/fattree.hpp \
    src/networks/flatfly_onchip.hpp \
    src/networks/fly.hpp \
    src/networks/kncube.hpp \
    src/networks/network.hpp \
    src/networks/qtree.hpp \
    src/networks/tree4.hpp \
  	src/power/buffer_monitor.hpp \
    src/power/power_module.hpp \
    src/power/switch_monitor.hpp \
  	src/routers/chaos_router.hpp \
    src/routers/event_router.hpp \
    src/routers/iq_router.hpp \
    src/routers/router.hpp \
  	src/batchtrafficmanager.hpp \
  	src/booksim_config.hpp \
  	src/booksim.hpp \
    src/buffer_state.hpp \
  	src/buffer.hpp \
  	src/channel.hpp \
  	src/config_utils.hpp \
  	src/credit.hpp \
  	src/flit.hpp \
  	src/flitchannel.hpp \
  	src/globals.hpp \
  	src/injection.hpp \
  	src/misc_utils.hpp \
  	src/module.hpp \
  	src/outputset.hpp \
  	src/packet_reply_info.hpp \
  	src/pipefifo.hpp \
  	src/random_utils.hpp \
  	src/routefunc.hpp \
  	src/stats.hpp \
  	src/timed_module.hpp \
  	src/traffic.hpp \
  	src/trafficmanager.hpp \
  	src/vc.hpp 

libbooksim2_la_LDFLAGS = -module -avoid-version
all: all-am

.SUFFIXES:
.SUFFIXES: .cc .cpp .lo .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign src/sst/elements/booksim2/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign src/sst/elements/booksim2/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):

install-compLTLIBRARIES: $(comp_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(comp_LTLIBRARIES)'; test -n "$(compdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(compdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(compdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(compdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(compdir)"; \
	}

uninstall-compLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(comp_LTLIBRARIES)'; test -n "$(compdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(compdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(compdir)/$$f"; \
	done

clean-compLTLIBRARIES:
	-test -z "$(comp_LTLIBRARIES)" || rm -f $(comp_LTLIBRARIES)
	@list='$(comp_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}
src/allocators/$(am__dirstamp):
	@$(MKDIR_P) src/allocators
	@: > src/allocators/$(am__dirstamp)
src/allocators/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/allocators/$(DEPDIR)
	@: > src/allocators/$(DEPDIR)/$(am__dirstamp)
src/allocators/allocator.lo: src/allocators/$(am__dirstamp) \
	src/allocators/$(DEPDIR)/$(am__dirstamp)
src/allocators/islip.lo: src/allocators/$(am__dirstamp) \
	src/allocators/$(DEPDIR)/$(am__dirstamp)
src/allocators/loa.lo: src/allocators/$(am__dirstamp) \
	src/allocators/$(DEPDIR)/$(am__dirstamp)
src/allocators/maxsize.lo: src/allocators/$(am__dirstamp) \
	src/allocators/$(DEPDIR)/$(am__dirstamp)
src/allocators/pim.lo: src/allocators/$(am__dirstamp) \
	src/allocators/$(DEPDIR)/$(am__dirstamp)
src/allocators/selalloc.lo: src/allocators/$(am__dirstamp) \
	src/allocators/$(DEPDIR)/$(am__dirstamp)
src/allocators/separable_input_first.lo:  \
	src/allocators/$(am__dirstamp) \
	src/allocators/$(DEPDIR)/$(am__dirstamp)
src/allocators/separable.lo: src/allocators/$(am__dirstamp) \
	src/allocators/$(DEPDIR)/$(am__dirstamp)
src/allocators/wavefront.lo: src/allocators/$(am__dirstamp) \
	src/allocators/$(DEPDIR)/$(am__dirstamp)
src/arbiters/$(am__dirstamp):
	@$(MKDIR_P) src/arbiters
	@: > src/arbiters/$(am__dirstamp)
src/arbiters/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/arbiters/$(DEPDIR)
	@: > src/arbiters/$(DEPDIR)/$(am__dirstamp)
src/arbiters/arbiter.lo: src/arbiters/$(am__dirstamp) \
	src/arbiters/$(DEPDIR)/$(am__dirstamp)
src/arbiters/matrix_arb.lo: src/arbiters/$(am__dirstamp) \
	src/arbiters/$(DEPDIR)/$(am__dirstamp)
src/arbiters/prio_arb.lo: src/arbiters/$(am__dirstamp) \
	src/arbiters/$(DEPDIR)/$(am__dirstamp)
src/arbiters/roundrobin_arb.lo: src/arbiters/$(am__dirstamp) \
	src/arbiters/$(DEPDIR)/$(am__dirstamp)
src/arbiters/tree_arb.lo: src/arbiters/$(am__dirstamp) \
	src/arbiters/$(DEPDIR)/$(am__dirstamp)
src/learning/$(am__dirstamp):
	@$(MKDIR_P) src/learning
	@: > src/learning/$(am__dirstamp)
src/learning/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/learning/$(DEPDIR)
	@: > src/learning/$(DEPDIR)/$(am__dirstamp)
src/learning/dgb.lo: src/learning/$(am__dirstamp) \
	src/learning/$(DEPDIR)/$(am__dirstamp)
src/networks/$(am__dirstamp):
	@$(MKDIR_P) src/networks
	@: > src/networks/$(am__dirstamp)
src/networks/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/networks/$(DEPDIR)
	@: > src/networks/$(DEPDIR)/$(am__dirstamp)
src/networks/anynet.lo: src/networks/$(am__dirstamp) \
	src/networks/$(DEPDIR)/$(am__dirstamp)
src/networks/cmesh.lo: src/networks/$(am__dirstamp) \
	src/networks/$(DEPDIR)/$(am__dirstamp)
src/networks/dragonfly.lo: src/networks/$(am__dirstamp) \
	src/networks/$(DEPDIR)/$(am__dirstamp)
src/networks/fattree.lo: src/networks/$(am__dirstamp) \
	src/networks/$(DEPDIR)/$(am__dirstamp)
src/networks/flatfly_onchip.lo: src/networks/$(am__dirstamp) \
	src/networks/$(DEPDIR)/$(am__dirstamp)
src/networks/fly.lo: src/networks/$(am__dirstamp) \
	src/networks/$(DEPDIR)/$(am__dirstamp)
src/networks/kncube.lo: src/networks/$(am__dirstamp) \
	src/networks/$(DEPDIR)/$(am__dirstamp)
src/networks/network.lo: src/networks/$(am__dirstamp) \
	src/networks/$(DEPDIR)/$(am__dirstamp)
src/networks/qtree.lo: src/networks/$(am__dirstamp) \
	src/networks/$(DEPDIR)/$(am__dirstamp)
src/networks/tree4.lo: src/networks/$(am__dirstamp) \
	src/networks/$(DEPDIR)/$(am__dirstamp)
src/power/$(am__dirstamp):
	@$(MKDIR_P) src/power
	@: > src/power/$(am__dirstamp)
src/power/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/power/$(DEPDIR)
	@: > src/power/$(DEPDIR)/$(am__dirstamp)
src/power/buffer_monitor.lo: src/power/$(am__dirstamp) \
	src/power/$(DEPDIR)/$(am__dirstamp)
src/power/power_module.lo: src/power/$(am__dirstamp) \
	src/power/$(DEPDIR)/$(am__dirstamp)
src/power/switch_monitor.lo: src/power/$(am__dirstamp) \
	src/power/$(DEPDIR)/$(am__dirstamp)
src/routers/$(am__dirstamp):
	@$(MKDIR_P) src/routers
	@: > src/routers/$(am__dirstamp)
src/routers/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/routers/$(DEPDIR)
	@: > src/routers/$(DEPDIR)/$(am__dirstamp)
src/routers/chaos_router.lo: src/routers/$(am__dirstamp) \
	src/routers/$(DEPDIR)/$(am__dirstamp)
src/routers/event_router.lo: src/routers/$(am__dirstamp) \
	src/routers/$(DEPDIR)/$(am__dirstamp)
src/routers/iq_router.lo: src/routers/$(am__dirstamp) \
	src/routers/$(DEPDIR)/$(am__dirstamp)
src/routers/router.lo: src/routers/$(am__dirstamp) \
	src/routers/$(DEPDIR)/$(am__dirstamp)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/batchtrafficmanager.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/booksim_config.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/buffer_state.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/buffer.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/config_utils.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/credit.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/flit.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/flitchannel.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/injection.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/misc_utils.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/module.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/outputset.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/packet_reply_info.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/random_utils.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/rng_double_wrapper.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/rng_wrapper.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/routefunc.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/stats.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/traffic.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/trafficmanager.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/vc.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)

libbooksim2.la: $(libbooksim2_la_OBJECTS) $(libbooksim2_la_DEPENDENCIES) $(EXTRA_libbooksim2_la_DEPENDENCIES) 
	$(AM_V_CXXLD)$(libbooksim2_la_LINK) -rpath $(compdir) $(libbooksim2_la_OBJECTS) $(libbooksim2_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/*.$(OBJEXT)
	-rm -f src/*.lo
	-rm -f src/allocators/*.$(OBJEXT)
	-rm -f src/allocators/*.lo
	-rm -f src/arbiters/*.$(OBJEXT)
	-rm -f src/arbiters/*.lo
	-rm -f src/learning/*.$(OBJEXT)
	-rm -f src/learning/*.lo
	-rm -f src/networks/*.$(OBJEXT)
	-rm -f src/networks/*.lo
	-rm -f src/power/*.$(OBJEXT)
	-rm -f src/power/*.lo
	-rm -f src/routers/*.$(OBJEXT)
	-rm -f src/routers/*.lo

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/booksim2.Plo
include ./$(DEPDIR)/booksimBridge.Plo
include ./$(DEPDIR)/booksimInterface.Plo
include src/$(DEPDIR)/batchtrafficmanager.Plo
include src/$(DEPDIR)/booksim_config.Plo
include src/$(DEPDIR)/buffer.Plo
include src/$(DEPDIR)/buffer_state.Plo
include src/$(DEPDIR)/config_utils.Plo
include src/$(DEPDIR)/credit.Plo
include src/$(DEPDIR)/flit.Plo
include src/$(DEPDIR)/flitchannel.Plo
include src/$(DEPDIR)/injection.Plo
include src/$(DEPDIR)/misc_utils.Plo
include src/$(DEPDIR)/module.Plo
include src/$(DEPDIR)/outputset.Plo
include src/$(DEPDIR)/packet_reply_info.Plo
include src/$(DEPDIR)/random_utils.Plo
include src/$(DEPDIR)/rng_double_wrapper.Plo
include src/$(DEPDIR)/rng_wrapper.Plo
include src/$(DEPDIR)/routefunc.Plo
include src/$(DEPDIR)/stats.Plo
include src/$(DEPDIR)/traffic.Plo
include src/$(DEPDIR)/trafficmanager.Plo
include src/$(DEPDIR)/vc.Plo
include src/allocators/$(DEPDIR)/allocator.Plo
include src/allocators/$(DEPDIR)/islip.Plo
include src/allocators/$(DEPDIR)/loa.Plo
include src/allocators/$(DEPDIR)/maxsize.Plo
include src/allocators/$(DEPDIR)/pim.Plo
include src/allocators/$(DEPDIR)/selalloc.Plo
include src/allocators/$(DEPDIR)/separable.Plo
include src/allocators/$(DEPDIR)/separable_input_first.Plo
include src/allocators/$(DEPDIR)/wavefront.Plo
include src/arbiters/$(DEPDIR)/arbiter.Plo
include src/arbiters/$(DEPDIR)/matrix_arb.Plo
include src/arbiters/$(DEPDIR)/prio_arb.Plo
include src/arbiters/$(DEPDIR)/roundrobin_arb.Plo
include src/arbiters/$(DEPDIR)/tree_arb.Plo
include src/learning/$(DEPDIR)/dgb.Plo
include src/networks/$(DEPDIR)/anynet.Plo
include src/networks/$(DEPDIR)/cmesh.Plo
include src/networks/$(DEPDIR)/dragonfly.Plo
include src/networks/$(DEPDIR)/fattree.Plo
include src/networks/$(DEPDIR)/flatfly_onchip.Plo
include src/networks/$(DEPDIR)/fly.Plo
include src/networks/$(DEPDIR)/kncube.Plo
include src/networks/$(DEPDIR)/network.Plo
include src/networks/$(DEPDIR)/qtree.Plo
include src/networks/$(DEPDIR)/tree4.Plo
include src/power/$(DEPDIR)/buffer_monitor.Plo
include src/power/$(DEPDIR)/power_module.Plo
include src/power/$(DEPDIR)/switch_monitor.Plo
include src/routers/$(DEPDIR)/chaos_router.Plo
include src/routers/$(DEPDIR)/event_router.Plo
include src/routers/$(DEPDIR)/iq_router.Plo
include src/routers/$(DEPDIR)/router.Plo

.cc.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cc.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cc.lo:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CXX)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LTCXXCOMPILE) -c -o $@ $<

.cpp.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CXX)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LTCXXCOMPILE) -c -o $@ $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf src/.libs src/_libs
	-rm -rf src/allocators/.libs src/allocators/_libs
	-rm -rf src/arbiters/.libs src/arbiters/_libs
	-rm -rf src/learning/.libs src/learning/_libs
	-rm -rf src/networks/.libs src/networks/_libs
	-rm -rf src/power/.libs src/power/_libs
	-rm -rf src/routers/.libs src/routers/_libs

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES)
installdirs:
	for dir in "$(DESTDIR)$(compdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)
	-rm -f src/allocators/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/allocators/$(am__dirstamp)
	-rm -f src/arbiters/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/arbiters/$(am__dirstamp)
	-rm -f src/learning/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/learning/$(am__dirstamp)
	-rm -f src/networks/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/networks/$(am__dirstamp)
	-rm -f src/power/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/power/$(am__dirstamp)
	-rm -f src/routers/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/routers/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-compLTLIBRARIES clean-generic clean-libtool \
	mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR) src/$(DEPDIR) src/allocators/$(DEPDIR) src/arbiters/$(DEPDIR) src/learning/$(DEPDIR) src/networks/$(DEPDIR) src/power/$(DEPDIR) src/routers/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-compLTLIBRARIES

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am:

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR) src/$(DEPDIR) src/allocators/$(DEPDIR) src/arbiters/$(DEPDIR) src/learning/$(DEPDIR) src/networks/$(DEPDIR) src/power/$(DEPDIR) src/routers/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-compLTLIBRARIES

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am check check-am clean \
	clean-compLTLIBRARIES clean-generic clean-libtool \
	cscopelist-am ctags ctags-am distclean distclean-compile \
	distclean-generic distclean-libtool distclean-tags distdir dvi \
	dvi-am html html-am info info-am install install-am \
	install-compLTLIBRARIES install-data install-data-am \
	install-dvi install-dvi-am install-exec install-exec-am \
	install-html install-html-am install-info install-info-am \
	install-man install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-compLTLIBRARIES


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
